// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
<<<<<<< HEAD
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";
=======
import "dotenv/config";
import { defineConfig, PrismaConfig } from "prisma/config";

export interface ExtendedPrismaConfig extends PrismaConfig {
  migrations?: {
    path: string;
  };
}
>>>>>>> f560fe8db39d3cd7a8eba3363cc7302f8d5eed20

dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
} as unknown as ExtendedPrismaConfig);
