// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, PrismaConfig } from "prisma/config";

export interface ExtendedPrismaConfig extends PrismaConfig {
  migrations?: {
    path: string;
  };
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
} as unknown as ExtendedPrismaConfig);
